### ISSUE TITLE
Parents get full access rights by default

### ISSUE THREAD

**Issue by ajinkyagadewar** [JayVora-SerpentCS/OdooEduERP#100]
Parents get full access rights by default which is major bug in the system.

**Comment by JayVora-SerpentCS** [comment]
@ajinkyagadewar Please explain by example.

**Comment by ajinkyagadewar** [comment]
Sure. Whenever I create a new student in the system with Parent details, it creates a new user for Parent too. That new user get all permissions in Odoo.

**Comment by Arpit-SerpentCS** [comment]
solved #109
