### ISSUE TITLE
Can't create student

### ISSUE THREAD

**Issue by emileboshoff** [JayVora-SerpentCS/OdooEduERP#11]
Hi, 

Please could you assist with the following error I keep on getting when trying to create a student or clicking on "Admission Register"

ProgrammingError: invalid reference to FROM-clause entry for table "res_users"
LINE 2: ..."user_id" = "student_student__user_id"."id") AND ("res_users...
                                                             ^
HINT:  Perhaps you meant to reference the table alias "student_student__user_id".

![school error](https://cloud.githubusercontent.com/assets/10843182/12298614/bb24ea5a-ba1b-11e5-8f9f-25d43658e695.png)

Thank you very much
Emile

**Comment by JayVora-SerpentCS** [comment]
Emile,
This is an official odoo issue and has been already fixed. Would you please make sure to have the latest version?
Thanks.
