### ISSUE TITLE
Parent

### ISSUE THREAD

**Issue by bidish** [JayVora-SerpentCS/OdooEduERP#111]
parent can not see student

**Comment by JayVora-SerpentCS** [comment]
Please specify the steps.
Cc : @Arpit-SerpentCS

**Comment by bidish** [comment]
Create ParentCreate Student and add parentLogin as parent.

Sent from Yahoo Mail on Android 
 
  On Tue, Aug 14, 2018 at 12:21, Serpent Consulting Services Pvt. Ltd.<notifications@github.com> wrote:   
Please specify the steps.
Cc : @Arpit-SerpentCS

**Comment by bidish** [comment]
Steps to repoduce:
Create Parent
Create Student Profile
Add Parent.
Login  as parent and click of student. The record added does not show.

**Comment by Arpit-SerpentCS** [comment]
@bidish  Can you please check the allowed companies are same for parent and its related student?
I think the parent's company is different from student's company.

**Comment by JayVora-SerpentCS** [comment]
Closing this as it seems old one. If it comes again, we may reopen.
