### ISSUE TITLE
[WISHLIST] v13 - Suggestions Regarding Fee Module

### ISSUE THREAD

**Issue by inovtec-solutions** [JayVora-SerpentCS/OdooEduERP#112]
Dears, 
I am working with your Education ERP, I have some suggestions regarding "Fee Module".
Why we not including product for students invoices, as produt id is empty.

See below image for reference
![selection_023](https://user-images.githubusercontent.com/9356127/44139237-e944cb5a-a08f-11e8-9a90-c1b2ba0ebc4e.jpg)

Generally, we have a Fee Structure like (Normal Fee, Employee Son Fee, Scholarship Fee etc) ...
Every Fee Structure has its own Fee Heads but with different amounts like;
Normal Fee: Admission Fee (5000), Tuition Fee (1500), and Security (2000)
Employee Son Fee: Admission Fee (2500), Tuition Fee (750), and Security Fee (2000)
Scholarship Fee: Admission Fee (500), Tuition Fee (300), and Security Fee (2000)

We can do this bifurcation in two ways;

1) . One way is to define different heads and fee structures as you did in your OdooEduERP.
2) . Use Product and Product Lists (My Suggestions):

       i).   Create Fee Heads (Admission, Tuition, Security etc), but instead amount, relate Product as Many2one.
       ii).  Define One Fee Structure For Every Class/Program/Course with One2many Fee Heads as (OdooEduERP)
       iii). On Fee Receipts, select "Fee Structure" as defined for Class/Program/Course.
       iv).  Select Product List as applied fees for that specific student/s.

See below images for reference
![selection_025](https://user-images.githubusercontent.com/9356127/44139239-e98943f2-a08f-11e8-9055-2ccd64818b2f.jpg)
![selection_026](https://user-images.githubusercontent.com/9356127/44139240-e9b473a6-a08f-11e8-9f64-e1bb7fd77ae2.jpg)

Regards

**Comment by JayVora-SerpentCS** [comment]
Sure, a good suggestion.  You may add this into contribution if you feel any change needed.

**Comment by kyaranusa** [comment]
I think this is a good suggestion and brilliant idea as well. OpenEduCat System doesn't have own fee head and fee structure. they let "product list" as a service take over for doing such our fee head & fee structure.

**Comment by JayVora-SerpentCS** [comment]
@AnuKPatel please keep in TODO.

**Comment by AnuKPatel** [comment]
Added improvements as per described here in v15.
@JayVora-SerpentCS Please close the issue.
