### ISSUE TITLE
"Assign Assignment" & Class/Subject/Teacher Issue

### ISSUE THREAD

**Issue by probasse** [JayVora-SerpentCS/OdooEduERP#115]
There are two issues.
A teacher "Malli" is assigned the subject "Maths" & Class Teacher for Class "Three";
"Maths" is a subject for Classes "One", "Two", "Three" and "Four".
When "Assign Assignment" is chosen to create a assignment for Subject "Maths" to Class "Two" the issue are
(1) Only Class Three is showing up in the Dropdown for Class.
(2) There is no Subject showing up in the Dropdown for Subject.

**Comment by AnuKPatel** [comment]
@probasse ,
Seems like these issues are because of Configuration is not Proper.

(1) Only Class Three is created for school to which Teacher "Malli" is working in.
(2) You need to select the subject in Teacher's Form for which teacher responsible for.
