### ISSUE TITLE
Module report not found

### ISSUE THREAD

**Issue by Johan-Kenneth** [JayVora-SerpentCS/OdooEduERP#116]
When I try to install one of the module developped , I get this message : 
"Vous essayez d'installer le module "school" qui dépend du module "report".
Mais ce dernier n'est pas disponible sur votre système."
Please where can I find the module "report"?

**Comment by JayVora-SerpentCS** [comment]
@AnuKPatel

**Comment by JayVora-SerpentCS** [comment]
Which version are you trying @Johan-Kenneth  ?

**Comment by Johan-Kenneth** [comment]
I downloaded the version from here, I think it is the last version.
When I go in the properties of the school module ,I find that the state of the dependance is unknow...
I have installed the module intrastat reporting base, I don't know if "report" is talking about that.

**Comment by Johan-Kenneth** [comment]
I have found that in the module school : 
'depends': ['hr', 'crm', 'report', 'account', 'account_accountant'],
The dependence report here is not found in my odoo version (12) but I found all the rest.

**Comment by Johan-Kenneth** [comment]
I have found that in the module school in the manifest file : 
'depends': ['hr', 'crm', 'report', 'account', 'account_accountant'],
The dependence report here is not found in my odoo version (12) but I found all the rest.
https://github.com/odoo/odoo/tree/12.0/addons
https://apps.odoo.com/apps/modules/browse?price=Free&search=report
May be you have implement a module report.

**Comment by JayVora-SerpentCS** [comment]
Seems you are using v10 source with v12 odoo. 
https://github.com/JayVora-SerpentCS/OdooEduERP/blob/12.0/school/__manifest__.py does not have report.

**Comment by Johan-Kenneth** [comment]
thank you very much, I will try it.
