### ISSUE TITLE
I Can't create student V10

### ISSUE THREAD

**Issue by lammh** [JayVora-SerpentCS/OdooEduERP#126]
hello , i can't create a new student
i have install all modules and have all permission
![studiant](https://user-images.githubusercontent.com/7395544/50136794-2d040200-0299-11e9-95a8-91c6782506f6.png)

![st2](https://user-images.githubusercontent.com/7395544/50136816-473de000-0299-11e9-8b8c-28cec6b4e7e7.png)
![admin](https://user-images.githubusercontent.com/7395544/50136830-5a50b000-0299-11e9-82a4-3376b89af5a9.png)

**Comment by AnuKPatel** [comment]
@lammh ,
Please select only one access of School administrator and remove all other Access groups from School Management section.

**Comment by ccysfn** [comment]
i have this issue too on odooV12

**Comment by JayVora-SerpentCS** [comment]
@AnuKPatel plz chk

**Comment by AnuKPatel** [comment]
@ccysfn You can create new students from EMS > Admission Register.
The flow is like Student will take admission first, so School admin will create record in Admission Register. After all the required details are filled up there is button called 'Done', by click on that button the admission is confirmed of the student and his/her profile is created which you can see from EMS > Profiles > Student Profile.
Let us know if you are facing any issues.
Thanks.
