### ISSUE TITLE
  problem when creating new admission record V11

### ISSUE THREAD

**Issue by grupokam** [JayVora-SerpentCS/OdooEduERP#128]
when I want to make a new record from another user that is not the administrator it gives me a writing problem and in other users it gives me problems when generating the student id since it only remains as new

![image](https://user-images.githubusercontent.com/46513856/50878891-78906400-139e-11e9-8609-86fd8b7e33ec.png)

As you can see in the image the student id remains as false and does not give a correlative
Thank you in advance for your cooperation.

**Comment by JayVora-SerpentCS** [comment]
@AnuKPatel check

**Comment by AnuKPatel** [comment]
Resolve in [PR](https://github.com/JayVora-SerpentCS/OdooEduERP/pull/135).
