### ISSUE TITLE
French localisation in demo data

### ISSUE THREAD

**Issue by mamaf** [JayVora-SerpentCS/OdooEduERP#13]
The demo data needs to take into account the french localisation for dates, otherwise the installation doesn't work

In demo_data.xml : dates are calculated but in wrong format for french localisation

there is still a problem with week_day calculation
the function give the week_day in french
and the time_table_line expects week_day in english

**Comment by JayVora-SerpentCS** [comment]
Agreed, we have started working on it, shall see in v9 onwards.
Thanks.
