### ISSUE TITLE
[WISHLIST] v13 - Age of student should be greater than 5 years!

### ISSUE THREAD

**Issue by seanmavley** [JayVora-SerpentCS/OdooEduERP#133]
To decrease this student age threshold, how do I go about it?

Use case is a pre-school

**Comment by AnuKPatel** [comment]
@seanmavley ,

Currently this age constrain of 5 years is static as the functionality is for school (not pre-school), you can not change it from GUI.

**Comment by JayVora-SerpentCS** [comment]
@seanmavley we can develop a configurable option further in v13. @JagdishPanchalSCS plz note this.

**Comment by JayVora-SerpentCS** [comment]
will be covered in v14. Thanks,
