### ISSUE TITLE
can't create school

### ISSUE THREAD

**Issue by kwchan-mtsoln** [JayVora-SerpentCS/OdooEduERP#153]
The requested operation cannot be completed due to security restrictions. Please contact your system administrator. (Document type: School Information, Operation: create) - (Records: [7], User: 6) 

all access rights are set

**Comment by JayVora-SerpentCS** [comment]
@dhruvitaSerpentCS

**Comment by dhruvitaSerpentCS** [comment]
@heero0910 I have tested the same thing with latest code, It's working well!.
Would you please take latest pull and check it
Thanks
