### ISSUE TITLE
Can't create class!!

### ISSUE THREAD

**Issue by Assoum90** [JayVora-SerpentCS/OdooEduERP#156]
Hi, I am using School module.
I have some issues that needs to be clarified In the class field i want to add some student to different classes, however it requires to add the school_id unfortunately i cant find it's place to fill it as it appears in the screenshot attached.
Please help me.
![image (13)](https://user-images.githubusercontent.com/53982488/72873709-c39ec000-3cf0-11ea-92d3-3f44b1faabf5.png)

**Comment by JayVora-SerpentCS** [comment]
@Assoum90 the school is the parent model which needs to be filled in before you create class.
You should import school first.

**Comment by JayVora-SerpentCS** [comment]
@AnuKPatel We have to fix as major users face issue in creating class, being unable to do so.

**Comment by shahnoorafreen** [comment]
Hi,
i have installed your app just now. i am unable to create class since its showing import button instead of create button also note that i have created school filled details and saved . i have attached screenshot below please help me out with the problem, thank you
![Capture](https://user-images.githubusercontent.com/75296632/112723172-b1d53000-8f26-11eb-8b8b-aa70b8f823ff.JPG)

**Comment by AnuKPatel** [comment]
@Assoum90 @shahnoorafreen 
We are checking this issue and update you here ASAP.
Meanwhile can you please provide the details like which odoo version you are using and with which user are you logged in?

**Comment by shahnoorafreen** [comment]
Hi,

I am using odoo version 13 and logged in as admin.

Thanks & Regards
Shahnoor afreen

**Comment by AnuKPatel** [comment]
@shahnoorafreen @Assoum90 

The issue is because of the view.
You will find a create button by switching the view to List from kanban.
Here is the screen recording to help you out. [How to Do so!](https://drive.google.com/file/d/1agfZ_7eLyuXaX9sNjE_d8oWWbpldQup0/view?usp=sharing)

**Comment by shahnoorafreen** [comment]
Thank you so much serpent team is the best!

Thanks & Regards
Shahnoor afreen
