### ISSUE TITLE
Required fields

### ISSUE THREAD

**Issue by AnonJervis** [JayVora-SerpentCS/OdooEduERP#157]
Just want to say these are great modules.

I got a few questions. Are there anyway to make middle name not a requirement? Some of our students don't have a middle name so its very unnecessary to add them. 

Furthermore, I am having trouble finding where to create campus because it is a required field and I cannot create teacher's without it.

Are there documentations for OdooEduERP? I've been looking everywhere and I was hoping to solve these issues myself.

Thanks!

**Comment by JayVora-SerpentCS** [comment]
@AnonJervis ,
Yes you may make any field required/non-required. Thats technical.
About Campus, its a 'school' treated as campus. Go in configuration and make a school.
Thanks.

**Comment by AnonJervis** [comment]
I did create a school but the campus field does not show so I cannot populate it. Furthermore, I cannot uncheck field to non-required because it said I cannot make that change unless I change it in the python codes and best to make a new custom module.

Please have a look at the screenshot. I have tried reinstalling odoo serveral times and on different machines and it still doesn't show campus option after i setup school. I have also tried downloading the module here and in odoo app website as well but to no avail.

![odooeduerp](https://user-images.githubusercontent.com/59471184/75661803-f1403700-5ca8-11ea-8218-5cea511a1254.png)

**Comment by JayVora-SerpentCS** [comment]
@JagdishPanchalSCS

**Comment by JagdishPanchalSCS** [comment]
@AnonJervis 

"Campus" Value show based on "Responsibility of", So when you select a value in "Responsibility of" Campus will automatically show you.

**Comment by AnonJervis** [comment]
I see it now. This is very different because in Odoo11 you do not need to input "responsibility of" and can select their roles after teacher creation. May I suggest implementing the same option as in Odoo11?

Thanks!

**Comment by JayVora-SerpentCS** [comment]
Make a PR my friend
