### ISSUE TITLE
There is no current Academic Year defined!Please contact to Administator!

### ISSUE THREAD

**Issue by godlove94** [JayVora-SerpentCS/OdooEduERP#163]
Good Please am just new to the EMS. please I got this issue on version 12 when starting and Admission Register
please someone can help I have already created a year under configuration>academic year

![Screenshot from 2020-06-15 17-11-27](https://user-images.githubusercontent.com/55757905/84681612-4b010000-af2c-11ea-84b5-7b31b55c26fc.png)

**Comment by inovtec-solutions** [comment]
Just activate the Academic Year you have created.

**Comment by godlove94** [comment]
thanks is ok 

very grateful for the fast respond
