### ISSUE TITLE
Student Monthly Attendance Report

### ISSUE THREAD

**Issue by sektideface** [JayVora-SerpentCS/OdooEduERP#164]
File "c:\bitnami\odoo-12.0.20200215-0\apps\odoo\lib\site-packages\odoo-12.0.post20200215-py3.7.egg\odoo\addons\base\models\ir_actions_report.py", line 768, in _get_rendering_context
    data.update(report_model._get_report_values(docids, data=data))
AttributeError: 'report.school_attendance.attendance_month' object has no attribute '_get_report_values'

**Comment by JayVora-SerpentCS** [comment]
@AnuKPatel

**Comment by AnuKPatel** [comment]
@sektideface We will check and update you ASAP. cc @JayVora-SerpentCS

**Comment by sektideface** [comment]
thanks @AnuKPatel ,hope the issues can be fix ,and i will be waiting for the update.

**Comment by AnuKPatel** [comment]
@sektideface We have checked in every possible scenario to regenerate this issue at our end but everything seems to be working fine with odoo12. 

We have check odoo v12 as in the log you have shared it's "odoo-12.0.20200215-0". May I know if you are using another odoo version?
