### ISSUE TITLE
no create option for classes

### ISSUE THREAD

**Issue by godlove94** [JayVora-SerpentCS/OdooEduERP#165]
please there is not a create a new classes option!! all I see is just the import option
![Screenshot from 2020-07-27 17-35-44](https://user-images.githubusercontent.com/55757905/88567648-b1029c00-d02f-11ea-9926-9795229b5d6a.png)

**Comment by JayVora-SerpentCS** [comment]
@AnuKPatel plz check,

**Comment by godlove94** [comment]
Hello, good day!

please no update on this issue??

**Comment by godlove94** [comment]
I successfully import a class before the create option come now

**Comment by sluggogle** [comment]
I confirm that on a fresh install even after creating school/division/medium/classroom/subjects, you can only import Classes and not create
