### ISSUE TITLE
Odoo 12 can't confirm a Fees Register !!1

### ISSUE THREAD

**Issue by godlove94** [JayVora-SerpentCS/OdooEduERP#166]
error : The requested operation cannot be completed due to security restrictions. Please contact your system administrator.
(Document type: Student PaySlip, Operation: create) - (Records: [6], User: 2)

![Screenshot from 2020-08-04 12-17-08](https://user-images.githubusercontent.com/55757905/89288234-32b88200-d64d-11ea-8bba-1fc2f3030694.png)

**Comment by JayVora-SerpentCS** [comment]
@godlove94 What is the user access?
In order to generate a fee, you need to be in a group that allows this access.
https://github.com/JayVora-SerpentCS/OdooEduERP/blob/12.0/school_fees/security/security_fees.xml

**Comment by godlove94** [comment]
Please help m out on how to give allows this access

**Comment by JayVora-SerpentCS** [comment]
Go to the settings of user and allow access. cc @AnuKPatel

**Comment by AnuKPatel** [comment]
@godlove94 Can you please share a screenshot of setting>users>Administrator From here? I think you have set up user role inappropriately. cc @JayVora-SerpentCS

**Comment by godlove94** [comment]
ok!!! please see screeshot below

![Screenshot from 2020-08-06 13-06-35](https://user-images.githubusercontent.com/55757905/89530103-d2107d00-d7e5-11ea-9d16-2d40d3ed3309.png)
![Screenshot from 2020-08-06 13-06-53](https://user-images.githubusercontent.com/55757905/89530109-d50b6d80-d7e5-11ea-8737-1402d01e5c9b.png)
