### ISSUE TITLE
[WISHLIST] v13 can't create school fees register

### ISSUE THREAD

**Issue by godlove94** [JayVora-SerpentCS/OdooEduERP#178]
Please I got this message when trying to create a Fees Register and also when I select a Fees structure the amount doesn't appear during the creation of a Fees Register as shown on the screenshot below, also see below the message error

The requested operation ("create" on "Student PaySlip" (student.payslip)) was rejected because of the following rules:
- Student Fees Record Rule
- Parent Fees Record Rule

(Records: Registration fees (id=2), User: Administrator (id=2))

![Screenshot from 2020-08-25 08-29-27](https://user-images.githubusercontent.com/55757905/91147671-7d5b7600-e6b0-11ea-8dd4-0b9dc463da9d.png)

**Comment by JayVora-SerpentCS** [comment]
@AnuKPatel

**Comment by godlove94** [comment]
Please no updates on these issue?

**Comment by AnuKPatel** [comment]
@godlove94 The user 'Administrator' having no access to Fees module.
You need to setup the user access control from Setting > User > Administrator.

Give School administrator access rights to this user.
