### ISSUE TITLE
warning in school install

### ISSUE THREAD

**Issue by nutcracker53** [JayVora-SerpentCS/OdooEduERP#19]
Hello
My name is Jimmi Imperial from the Philippines, I downloaded eduERPv8. When I tried to install school module I got this odoo warning - "You try to install 'school' that depends on module 'email template' but the latter module is not available in your system". The email template is already installed as per attached screenshot. Is there another email template to be installed? I checked the odoo Apps but could not find anything new, except for the email template which is already installed. Did I missed anything. Thanks
![emailtemplate](https://cloud.githubusercontent.com/assets/15701055/20637811/8695a4f8-b3cd-11e6-9593-283cc42f6cef.png)
my email  bicolano53@yahoo.com

**Comment by JayVora-SerpentCS** [comment]
We will check asap.

**Comment by JayVora-SerpentCS** [comment]
No, the error does not come at all.
