### ISSUE TITLE
V13 Can not create and start a new EXAM (missing exam schedule)

### ISSUE THREAD

**Issue by trixocom** [JayVora-SerpentCS/OdooEduERP#203]
Step to reproduce:
1 - I Installed OdooV13 from scratch, then cloned this repo, and installed school and exam+timetable, modules with demo data in a new database.
2- All demo data loaded succesfully 
3-Go to Exam menu, then Exam. and create a new exam for the already created timetable in demo.
4-I fill up the data, select Class
5-Goto Exm Schedule tab, and try to add a new item, but no results, blank.
As a result I can not START the exam.

This is the SQL excetuted when I click the dropdown button in Exam Schedule -> Class selection..

odoo.sql_db: query: SELECT "school_standard".id FROM "school_standard" WHERE FALSE AND ((("school_standard"."cmp_id" in (1))  OR  ("school_standard"."cmp_id" in (1,29,30,31)))  OR  "school_standard"."cmp_id" IS NULL ) ORDER BY "school_standard"."id"   limit 8 

As you can see there is a "WHERE FALSE" clause..
Thanks
Hector

**Comment by AnuKPatel** [comment]
@trixocom Please pull the latest code and check. The issue is resolved now.

Let us know if you face any other issue.
Thanks.
