### ISSUE TITLE
error install exam module

### ISSUE THREAD

**Issue by evansadji** [JayVora-SerpentCS/OdooEduERP#21]
Hii.. when i was trying to install EduERPv8-8.0 .. 
i was stuck with some error on exam module..
here's the log..
![screenshot 2016-12-08 12 55 46](https://cloud.githubusercontent.com/assets/10150411/21004232/e12f91d8-bd61-11e6-927a-224c4cee30ff.png)

**Comment by JayVora-SerpentCS** [comment]
We will review soon and fix it it appears.
Thanks for reporting.

**Comment by evansadji** [comment]
Hai JayVora
Thank's for reply.. i am waiting for the issue tobe fixed..

Regards
E.Adji
Thank you

**Comment by JayVora-SerpentCS** [comment]
Pull latest build, we have fixed it.

**Comment by evansadji** [comment]
Dear JayVora.
Awesome.. It worked like a champCool..
Thank's alot


Sent from my Samsung device

-------- Original message --------
