### ISSUE TITLE
got error :Student Attendance Sheet Sorry no matrix data to display

### ISSUE THREAD

**Issue by zeintiz** [JayVora-SerpentCS/OdooEduERP#210]
hi everybody

i install odoo 14 on ubuntu. 

i have problem to see daily attendance in school erp . i define new daily attendance sheet . but when i go to "fill students attendance" i got this message : 
Sorry no matrix data to display.

please help me to solve this problem!?
tankx in advance

![image](https://user-images.githubusercontent.com/32398254/158056358-fa628ae5-d3fb-41d1-8237-1a014b0dafe0.png)

**Comment by JayVora-SerpentCS** [comment]
@AnuKPatel

**Comment by zeintiz** [comment]
plz help? student attendance sheet didnt work correctly?? my odoo is 14. plz help?!!

**Comment by Nuradin2022** [comment]
1.Daily Attendance sheet not work  and  Monthly  Attendance not display Absent  and  present , Sorry no matrix data to display.

**Comment by Nuradin2022** [comment]
How to Solve  a problem Daily Attendance

**Comment by AnuKPatel** [comment]
@Nuradin2022 @zeintiz The code is updated now. Please check with the latest source code.

**Comment by geelaniconsultancy** [comment]
Hi,
Where to find the updated code?

**Comment by JayVora-SerpentCS** [comment]
@geelaniconsultancy Here you go : https://github.com/JayVora-SerpentCS/OdooEduERP/tree/15.0

**Comment by geelaniconsultancy** [comment]
any update for version 14?
