### ISSUE TITLE
Paid Amount and Remaining Amount do not update after paying the invoice in V15

### ISSUE THREAD

**Issue by anisus77** [JayVora-SerpentCS/OdooEduERP#214]
i tried all cases, switching from my campany(admision for student and creating hostel student) to the school campany created and still Paid Amount and Remaining Amount do not update, in hostel and in fees after paying the bill
![facture](https://user-images.githubusercontent.com/14073043/168448324-e324149d-6d71-45f3-baa1-60b75241bc45.png)
 
![hostel](https://user-images.githubusercontent.com/14073043/168448364-f80b36d7-4b77-4d0d-8577-194633dfa93c.png)

**Comment by AnuKPatel** [comment]
@anisus77 Let us check and get back to you on this.
