### ISSUE TITLE
Bulk Import Students and assign class, standard and division to it

### ISSUE THREAD

**Issue by geelaniconsultancy** [JayVora-SerpentCS/OdooEduERP#219]
Hi,
We are trying to bulk import students and assign them to a class.
While doing bulk import, we map the column of Class. In CSV we entered the Class as below values:
10
10th[A]
10th.
However, each time it throws an error saying no matching records found. 
Please let us know if we are missing something here.
Attached is the screenshot of errors that we are getting and the sheet that we are trying to import. 
https://drive.google.com/drive/folders/1PYlmjebZtBNSr3DF2hvEWOchVaJwr0PG

Odoo 15 CE

**Comment by JayVora-SerpentCS** [comment]
Its a typical odoo import and you have to make sure your relational records pre-exist.
Please see : https://www.odoo.com/documentation/15.0/applications/general/export_import_data.html
The many2one or many2many records you have, should be referred and imported in advance.
Thanks,

**Comment by geelaniconsultancy** [comment]
Hello,
Thank you for the quick reply.
We checked. The records exists. However it doesnt allow to import even then.

**Comment by JayVora-SerpentCS** [comment]
can you trace the create()?

**Comment by geelaniconsultancy** [comment]
We traced the create method.
The standard_id (Labelled as Class in bulk import) does not get through. It comes empty in the create method.
If we pass standard_id hard coded in the create method and do bulk import, the records are getting created.
