### ISSUE TITLE
Error in install school module.

### ISSUE THREAD

**Issue by nutcracker53** [JayVora-SerpentCS/OdooEduERP#22]
I installed a new instance of Odoo v9 community app on Ubuntu 16.04. I updated my Apps List to get the EduERPv8 modules. I tried to install it in two separate ways and got these errors.
1. I click on install button, see (1_school_install.jpg)
2. Got this odoo warning, see (2_odoo_warning.jpg)
3. this time, I click on the school bldg icon see (4school_community.jpg)
4. confirmation appear , see (5_install_community.jpg) I click on install button here
5. Got this internal server error, see (5_internal_server_error.jpg)

6.  I click on technical Data - Dependencies and noticed the email_template status is unknown.
     How can I correct this dependency issue.? see (6_email_template.jpg

Please help . I need to test your School App for my customer..Thanks
Jaime Imperial (nutcracker53@gmail.com)
![1_school_install](https://cloud.githubusercontent.com/assets/15701055/21013591/af5137fa-bd95-11e6-8a37-158105c033d1.jpg)
![2odoo_warning](https://cloud.githubusercontent.com/assets/15701055/21013603/b7ce4b3e-bd95-11e6-912c-0b8dfec46f66.jpg)
![4school_community](https://cloud.githubusercontent.com/assets/15701055/21013613/c358d7e4-bd95-11e6-8e15-424d663d2800.jpg)
![5_install_community](https://cloud.githubusercontent.com/assets/15701055/21013626/cf67da30-bd95-11e6-8e8d-3b4746f90778.jpg)
![5_internal_server_error](https://cloud.githubusercontent.com/assets/15701055/21013636/d7a35cb0-bd95-11e6-8e52-47efe3706c11.jpg)
![6_email_template](https://cloud.githubusercontent.com/assets/15701055/21013649/dfe23ea0-bd95-11e6-972e-920fdbc66986.jpg)

**Comment by JayVora-SerpentCS** [comment]
Dear, The problem seems more regarding a missing module 'email_template' in your addons, this should exist in your system as it is a part of official addons.
