### ISSUE TITLE
Unable to add amount

### ISSUE THREAD

**Issue by Sumairabroadpeak** [JayVora-SerpentCS/OdooEduERP#222]
Hi there,

I am trying to use School_Fee addon. I created fee heads and i am unable to add amount there as this feild is lock.  Based on fee heads i have created fee structure which i am using while generating a fee slip but nothing refelecting there.

Regards
[Fee head issue.webm](https://user-images.githubusercontent.com/88372038/198062850-4bb07d4c-4be0-426a-8759-778a63aca885.webm)

**Comment by AnuKPatel** [comment]
@Sumairabroadpeak ,

'**Amount**' field in Fees Head is auto computed from Product you are selecting. Sales Price of the Product will be auto fetched as Amount in Fees head.

Please refer to screenshots I am sharing here,
[Fees head](https://prnt.sc/B6WFADttn850)
[Product Form](https://prnt.sc/Qhx3xUTCdQpG)

Let us know if you still have any concern.

Thanks.
