### ISSUE TITLE
Missing email_template persists. Cannot install school module

### ISSUE THREAD

**Issue by nutcracker53** [JayVora-SerpentCS/OdooEduERP#23]
Dear Sir.
I did a fresh installation of ubuntu 16.04, Updated the OS. and installed a new instance of Odoo v10 community App. I downloaded the EduERPv8 branch 10 modules from your github site and I updated my Apps List to get the EduERPv8 modules. when I tried to install it, I still get the email_template problem. Pls see steps below :
 1. I also noticed that the school modules does not have icons. Is this okay? see (school_module.jpg)
 2. When I click on install.   Got this odoo warning, see (odoo_warning.jpg) 
The school module technical details shows "email_template status as unknown" (see unknown_ email template.jpg)
3. I check the odoo Settings .and I can see that the email_plate is installed. Or maybe , Is there another email_template that is needed? Where do I get this? see (installed_email_template.jpg)
Pls help. Thanks a lot.
![school_module](https://cloud.githubusercontent.com/assets/15701055/21126168/97fafd6e-c125-11e6-8c8a-00b972cce650.jpg)
![odoo_warning](https://cloud.githubusercontent.com/assets/15701055/21126177/a430c3ca-c125-11e6-9d52-2f602a2f1c9b.jpg)
![unknown_email_template](https://cloud.githubusercontent.com/assets/15701055/21126190/b1554738-c125-11e6-9ed1-9bfb3afce4cb.jpg
![installed_email_template](https://cloud.githubusercontent.com/assets/15701055/21126218/d3ea5fae-c125-11e6-92e1-2d5795a9dcfb.jpg)

**Comment by JayVora-SerpentCS** [comment]
Please pull the latest version, it has been fixed.
