### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by fvlasie** [JayVora-SerpentCS/OdooEduERP#51]
On Odoo 11.0 when I try to install, I get the message
 "You try to install module 'library' that depends on module 'account_accountant'"
When I click to install EducationERP: Install all the modules

**Comment by JayVora-SerpentCS** [comment]
@fvlasie We have yet to migrate to v11, its a  work in progress

**Comment by JayVora-SerpentCS** [comment]
https://github.com/JayVora-SerpentCS/OdooEduERP/tree/11.0
