### ISSUE TITLE
How can we migrate a student from one standard to another standard?

### ISSUE THREAD

**Issue by dansputy** [JayVora-SerpentCS/OdooEduERP#53]
How can we move a student from one standard to another after end of academic session?

**Comment by JayVora-SerpentCS** [comment]
We can upgrade by the standard change. Guess we have a new update over this utility.
CC @AnuKPatel please check.

**Comment by dansputy** [comment]
I appreciate your response but am not clear with your comments. I hope can make free donation when appropriate?
I look forward to know on how to migrate student from one standard to another standard.

**Comment by JayVora-SerpentCS** [comment]
@dansputy my comments mean, our team will look and update you.
In order to upgrade the student, once he passes exam he usually gets upgraded in my idea.
You can make donations for sure.Thanks.

**Comment by AnuKPatel** [comment]
@dansputy We have a menu called "Move Standards" for this which is under EMS > Configurations.

- You will get a pop-up after clicking the menu. 
- Pop-up will ask for the current Academic Year from which you need to move the students to next standard.
- If you have Classes which are well configured which the sequence then students will move to next Class(If Exam module is installed then the system will check the result of each student and move the student to next class if he/she is pass).

Hope this helps.

**Comment by dansputy** [comment]
Thanks for your time. I actually use the wizard but no effect.

**Comment by AnuKPatel** [comment]
@dansputy Can you please check the sequences of from and to classes under EMS > Configurations > Standards > Classes?
As mentioned earlier we need to have well configured sequence of Classes. For example, If sequence of current class is 5 than the next class sequence should be 6.
Thanks.
