### ISSUE TITLE
GPS Tracking of School Bus

### ISSUE THREAD

**Issue by ajinkyagadewar** [JayVora-SerpentCS/OdooEduERP#62]
Are you guys planning to integrate GPS tracking of School bus?

**Comment by JayVora-SerpentCS** [comment]
@ajinkyagadewar This will be an external integration, with GPS enabled devices ported on fleet.
Once there is a funders of the activity, we have in the roadmap.
Thanks.

**Comment by ajinkyagadewar** [comment]
How much fund do you think we need for this project?

**Comment by JayVora-SerpentCS** [comment]
There has to be a discussion done on contact@serpentcs.com 
Usually, we should list out feature, flow of it, then the efforts and funding.
Thanks.
