### ISSUE TITLE
Name at all places

### ISSUE THREAD

**Issue by ajinkyagadewar** [JayVora-SerpentCS/OdooEduERP#66]
Currently, at all locations like Admission Register, Fees Receipt, etc. system reflects first name of the student instead of full name.
![screen shot 2018-04-16 at 6 04 05 pm](https://user-images.githubusercontent.com/3275617/38809340-d18318da-41a0-11e8-9b1b-0a72e2052ba2.png)

**Comment by JayVora-SerpentCS** [comment]
We will consider it as a wishlist, thanks.
